package com.example.notification.filter;

import com.example.common.correlation.CorrelationIdConstants;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.MDC;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

/**
 * Reads the CorrelationId propagated by Gateway Service and
 * stores it in MDC (Mapped Diagnostic Context).
 *
 * This allows the CorrelationId to be automatically included
 * in application logs using the configured logging pattern.
 *
 * The CorrelationId is generated by Gateway Service and
 * propagated through request headers across all downstream
 * microservices for end-to-end request tracking.
 *
 * MDC is cleared after request processing to prevent
 * correlation data leakage between requests.
 */
@Component
public class CorrelationIdFilter
        extends OncePerRequestFilter {

    @Override
    protected void doFilterInternal(
            HttpServletRequest request,
            HttpServletResponse response,
            FilterChain filterChain)
            throws ServletException, IOException {

        String correlationId =
                request.getHeader(
                        CorrelationIdConstants.CORRELATION_ID
                );

        if (correlationId != null) {

            MDC.put(
                    CorrelationIdConstants.CORRELATION_ID,
                    correlationId
            );
        }

        try {
            filterChain.doFilter(request, response);
        } finally {
            MDC.clear();
        }
    }
}